# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 19 */1 * *"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Update Python Script
      run: |
        python python-app.py
    - name: Update README.md file
      run: | 
        git pull
        git add .
        git diff
        git config --local user.email "kms39273@catholic.ac.kr"
        git config --local user.name "luckyvickyricky"
        git commit -m "ci: automate README updates with latest blog posts"
        git push
